const SHIPMENT_STATUS = {
  CREATED: "CREATED",
  IN_TRANSIT: "IN_TRANSIT",
  DELIVERED: "DELIVERED",
  DELAYED: "DELAYED"
};

const TRANSACTION_TYPES = {
  SUPPLY: "SUPPLY",
  SALE: "SALE",
  ADJUSTMENT: "ADJUSTMENT"
};

module.exports = {
  SHIPMENT_STATUS,
  TRANSACTION_TYPES
};
